//  This code was originally generated by Terasic System Builder
//  then amended by AK
 
`default_nettype none // disallow associating new names with undeclared wires

module DE10_Lite_top( 
// keep the port declarations below (defined in the QSF file) and use these names in your design
	input 				ADC_CLK_10, MAX10_CLK1_50, MAX10_CLK2_50, 	// CLOCK
	output	[7:0] 	HEX0, HEX1, HEX2, HEX3, HEX4, HEX5, 			// SEG7, 6 pcs
	input		[1:0]		KEY,														// inverted push buttons, 2 pcs				
	output	[9:0]		LEDR,														// red LEDs, 10 pcs
	input 	[9:0]		SW															// slide switches, 10 pcs
);


// *** DO NOT EDIT THE CODE BELOW
	
	assign LEDR = SW;						// display waht is entered by SW (this design uses SW[9] only)

	assign HEX5[6:0] 	= 7'b_111_1111;				// switch OFF the HEXes	
	assign HEX4 		= 8'b_1111_1111;	
	assign HEX3[7:1] 	= 7'b_111_1111;	
	assign HEX2 		= 8'b_1111_1111;	
	assign HEX1 		= 8'b_1111_1111;
	assign HEX0[7:4]	= 4'b_1111;
	assign HEX0[2:0]	= 3'b_111;
	
// *** DO NOT EDIT THE CODE ABOVE																				



// *****************************************************************
// FOR THIS LAB USE: SW[w-1:0], SW[9], KEY[1] and KEY[0] as inputs; HEX5[7], HEX3[0] and HEX0[3] as outputs (1 for OFF)
// For your structural design: 
//				- declare the necessary wires first (outputs of G1 and G2; output ports can be used as inputs to gates); 
//				- provide one line of Verilog for every gate (5 gates then 5 lines)
// PUT ALL YOUR CODE BELOW THIS LINE

	wire wire_1, wire_2;
	
	nand G1 ( wire_1, SW[2], SW[1], SW[0] );
	
	xor  G2 ( wire_2, KEY[1], KEY[0] );
	
	nand G3 ( HEX3[0], wire_1, SW[9], wire_2 );
	
	xor  G4 ( HEX5[7], wire_1, HEX3[0] );
	
	nand G5 ( HEX0[3], HEX3[0], wire_2 );
	
// PUT ALL YOUR CODE ABOVE THIS LINE
// *****************************************************************


endmodule
